services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./database/inbox_service.sql:/docker-entrypoint-initdb.d/init_inbox_service.sql
  #     - ./database/community_service.sql:/docker-entrypoint-initdb.d/init_community_service.sql
  #     - ./database/content_moderation_service.sql:/docker-entrypoint-initdb.d/init_content_moderation_service.sql
  #     - ./database/comment_service.sql:/docker-entrypoint-initdb.d/init_comment_service.sql
  #     - ./database/post_service.sql:/docker-entrypoint-initdb.d/init_post_service.sql
  #     - ./database/community_members_service.sql:/docker-entrypoint-initdb.d/init_community_members_service.sql
  #     - ./database/email_service.sql:/docker-entrypoint-initdb.d/init_email_service.sql
  #     - ./database/events_service.sql:/docker-entrypoint-initdb.d/init_events_service.sql
  #     - ./database/events_registration.sql:/docker-entrypoint-initdb.d/init_events_registration.sql
  #     - mysql_data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   networks:
  #     - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  inbox_queue_consumer:
    build:
      context: ./backend/rabbitmq/inbox_queue
      dockerfile: Dockerfile
    container_name: inbox_queue_consumer
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - EXCHANGE_NAME=hangout_exchange
      - EXCHANGE_TYPE=direct
      - QUEUE_NAME=inbox
      - ROUTING_KEY=inbox_message
      - API_ENDPOINT=http://inbox_service:5006/api/inbox/create
    depends_on:
      - rabbitmq
      - inbox_service
    networks:
      - app-network

  event_registration_queue_consumer:
    build:
      context: ./backend/rabbitmq/event_registration_queue
      dockerfile: Dockerfile
    container_name: event_registration_queue_consumer
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - EXCHANGE_NAME=hangout_exchange
      - EXCHANGE_TYPE=direct
      - REGISTRATION_QUEUE_NAME=event_registration
      - REGISTRATION_ROUTING_KEY=event_registration
      - REGISTRATION_API_ENDPOINT=http://register_for_event_service:5010/api/register_internal
    depends_on:
      - rabbitmq
      - register_for_event_service
    networks:
      - app-network

  kong:
    image: kong/kong-gateway:3.9
    container_name: kong
    platform: linux/amd64
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/routes.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./backend/kong/routes.yaml:/etc/kong/routes.yaml
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    networks:
      - app-network

  user_service:
    build:
      context: ./backend/atomic/user_service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "5000:5000"
    environment:
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
    networks:
      - app-network

  community_service:
    build:
      context: ./backend/atomic/community_service
      dockerfile: Dockerfile
    container_name: community_service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=${DATABASE_URL}/community_service
    networks:
      - app-network

  post_service:
    build:
      context: ./backend/atomic/post_service
      dockerfile: Dockerfile
    container_name: post_service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=${DATABASE_URL}/post_service
    networks:
      - app-network

  comment_service:
    build:
      context: ./backend/atomic/comment_service
      dockerfile: Dockerfile
    container_name: comment_service
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=${DATABASE_URL}/comment_service
    networks:
      - app-network

  events_service:
    build:
      context: ./backend/atomic/events_service
      dockerfile: Dockerfile
    container_name: events_service
    ports:
      - "5004:5004"
    environment:
      - DATABASE_URL=${DATABASE_URL}/events_service
    networks:
      - app-network

  event_registration_service:
    build:
      context: ./backend/atomic/event_registration_service
      dockerfile: Dockerfile
    container_name: event_registration_service
    ports:
      - "5005:5005"
    environment:
      - DATABASE_URL=${DATABASE_URL}/event_registrations_database
    networks:
      - app-network

  inbox_service:
    build:
      context: ./backend/atomic/inbox_service
      dockerfile: Dockerfile
    container_name: inbox_service
    ports:
      - "5006:5006"
    environment:
      - DATABASE_URL=${DATABASE_URL}/inbox_service
    networks:
      - app-network
  content_moderation_service:
    build:
      context: ./backend/atomic/content_moderation_service
      dockerfile: Dockerfile
    container_name: content_moderation_service
    ports:
      - "5007:5007"
    environment:
      - DATABASE_URL=${DATABASE_URL}/content_moderation_service
    networks:
      - app-network

  email_service:
    build:
      context: ./backend/atomic/email_service
      dockerfile: Dockerfile
    container_name: email_service
    ports:
      - "5008:5008"
    environment:
      - DATABASE_URL=${DATABASE_URL}/email_service
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    networks:
      - app-network

  manage_event_service:
    build:
      context: ./backend/composite/manage_event_service
      dockerfile: Dockerfile
    container_name: manage_event_service
    ports:
      - "5009:5009"
    environment:
      - EVENTS_SERVICE_URL=http://events_service:5004
      - REGISTRATION_URL=http://event_registration_service:5005
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - EXCHANGE_NAME=hangout_exchange
      - ROUTING_KEY=inbox_message
    depends_on:
      - events_service
      - rabbitmq
    networks:
      - app-network

  register_for_event_service:
    build:
      context: ./backend/composite/register_for_event_service
      dockerfile: Dockerfile
    container_name: register_for_event_service
    ports:
      - "5010:5010"
    environment:
      - EVENT_SERVICE_URL=http://events_service:5004
      - REGISTRATION_URL=http://event_registration_service:5005
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - EXCHANGE_NAME=hangout_exchange
      - ROUTING_KEY=inbox_message
      - REGISTRATION_ROUTING_KEY=event_registration
    depends_on:
      - events_service
      - event_registration_service
      - rabbitmq
    networks:
      - app-network

  ban_content_service:
    build:
      context: ./backend/composite/ban_content_service
      dockerfile: Dockerfile
    container_name: ban_content_service
    ports:
      - "5011:5011"
    environment:
      - USER_SERVICE_URL=http://user_service:5000/api/users
      - EMAIL_SERVICE_URL=http://email_service:5008/api/email
      - POST_SERVICE_URL=http://post_service:5002/api/post
      - COMMENT_SERVICE_URL=http://comment_service:5003/api/comment
      - CONTENT_MODERATION_URL=http://content_moderation_service:5007/api/moderation
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - EXCHANGE_NAME=hangout_exchange
      - ROUTING_KEY=inbox_message
    depends_on:
      - user_service
      - email_service
      - post_service
      - content_moderation_service
      - rabbitmq
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - kong
      - user_service
      - community_service
      - post_service
      - comment_service
      - events_service
      - event_registration_service
      - inbox_service
      - content_moderation_service
      - email_service
      - manage_event_service
      - register_for_event_service
      - ban_content_service
      - rabbitmq
      - inbox_queue_consumer
      - event_registration_queue_consumer
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq_data:
  mysql_data:
