FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY event_registration_service.py .
COPY event_registration_model.py .
ENV FLASK_APP=event_registration_service.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5005
EXPOSE 5005
CMD ["flask", "run"]